version: '3.9'

services:
  synpress:
    container_name: synpress
    build: .
    environment:
      - DISPLAY=display:0.0
      - CYPRESS_PRIVATE_KEY_WITH_FUNDS=${CYPRESS_PRIVATE_KEY_WITH_FUNDS}
      # - CYPRESS_PROJECT_ID=${CYPRESS_PROJECT_ID}
      # - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SYNDEBUG=${SYNDEBUG}
    depends_on:
      - display
      - video
    entrypoint: []
    working_dir: /app
    volumes:
      - ./docker/videos:/app/tests/e2e/videos
      - ./docker/screenshots:/app/tests/e2e/screenshots
    command: >
      bash -c 'echo -n "======> local noVNC URL:
      http://localhost:8080/vnc.html?autoconnect=true " && npx wait-on
      http://display:8080 && echo -n "======> remote noVNC URL: " && curl -s
      ngrok:4040/api/tunnels | jq -r .tunnels[0].public_url && yarn test:e2e:anvil'
    networks:
      - x11

  display:
    container_name: display
    image: synthetixio/display:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
    ports:
      - '8080:8080'
    networks:
      - x11

  ngrok:
    profiles:
      - ngrok
    container_name: ngrok
    image: synthetixio/ngrok:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    ports:
      - '4040:4040'
    command: ['ngrok', 'http', 'display:8080', '--authtoken', '${NGROK_AUTH}']
    depends_on:
      - display
    networks:
      - x11

  video:
    container_name: video
    image: synthetixio/video:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
      - SE_SCREEN_WIDTH=${SE_SCREEN_WIDTH}
      - SE_SCREEN_HEIGHT=${SE_SCREEN_HEIGHT}
    depends_on:
      - display
    networks:
      - x11

  foundry:
    container_name: foundry
    image: synthetixio/foundry:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    command: ['anvil', '--fork-url', '${ANVIL_FORK_URL}']
    ports:
      - '8545:8545'
    networks:
      - x11

networks:
  x11:
