name: Synpress CI

on:
  push:
  pull_request:
    branches: [master, dev]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  audit:
    # run only on master/dev branch and pull requests
    if:
      github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-sec-tools:16.17-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      - name: Audit dependencies
        run: audit-ci --critical --report-type full

      - name: Lockfile lint
        run:
          lockfile-lint -p yarn.lock --type yarn --allowed-schemes "https:"
          "git+https:" --empty-hostname false

  build:
    needs: audit
    # run only on audit success or audit skipped
    if:
      always() && (needs.audit.result == 'success' || needs.audit.result ==
      'skipped')
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-node:16.17-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      - name: Set yarn cache directory
        run: yarn config set cache-folder .yarn-cache
        continue-on-error: true

      - uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # pin@v2
        with:
          path: |
            .yarn-cache
            node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
        continue-on-error: true

      - name: Install dependencies
        run: yarn --prefer-offline --no-audit

      - name: Lint
        # run only on master/dev branch and pull requests
        if:
          github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' ||
          github.event_name == 'pull_request'
        run: yarn lint:sarif

      - name: Upload lint results
        # run if lint failed and only on master/dev branch and pull requests
        if:
          always() && (github.ref == 'refs/heads/master' || github.ref ==
          'refs/heads/dev' || github.event_name == 'pull_request')
        uses: github/codeql-action/upload-sarif@b398f525a5587552e573b247ac661067fafa920b # pin@codeql-bundle-20210517
        with:
          sarif_file: lint-results.sarif
        continue-on-error: true

  e2e:
    needs: build
    # run only on master/dev branch
    if:
      github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-e2e:16.17-ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # pin@v2

      - name: Set yarn cache directory
        run: yarn config set cache-folder .yarn-cache
        continue-on-error: true

      - uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # pin@v2
        with:
          path: |
            .yarn-cache
            node_modules
          key: ${{ runner.os }}-yarn-v1-e2e-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-e2e-
        continue-on-error: true

      - name: Install dependencies
        run: yarn --prefer-offline --no-audit
        env:
          CYPRESS_CACHE_FOLDER:
            ${{ github.workspace }}/node_modules/.cache/Cypress

      - name: Run e2e tests
        run: yarn test:e2e:ci
        env:
          SKIP_METAMASK_SETUP: ${{ secrets.SKIP_METAMASK_SETUP }}
          CYPRESS_PRIVATE_KEY_WITH_FUNDS:
            ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_CACHE_FOLDER:
            ${{ github.workspace }}/node_modules/.cache/Cypress

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          path: |
            tests/e2e/videos
            tests/e2e/screenshots
        continue-on-error: true
