name: E2E CI

on:
  push:
  pull_request:
    branches: [master, dev]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      - name: Test
        uses: cypress-io/github-action@30008f1458a5a2c97054bfe118fe33d75976c482 # pin@v4
        with:
          install-command: yarn --frozen-lockfile --prefer-offline --no-audit
          command: yarn test:e2e:ci
        env:
          CYPRESS_PRIVATE_KEY_WITH_FUNDS:
            ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
